#gcc is used for C compilation and g++ for C++ compilation

CC = gcc
CXX = g++

#Left blank as place holder for other directories
INCLUDES=

#Compilation options
#-g for debugging info and -Wall for enabling all warnings

CFLAGS = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

#Linking options
#-g used for debugging info

LDFLAGS = -G

#Listing all libraries that need to be linked for program to work
#-lm is used for the math library

LDLIBS = -lm

#Targets and dependencies

main: prime.o gcd.o

